-- MySQL Script generated by MySQL Workbench
-- Thu Nov 14 00:01:41 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydiary
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydiary
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydiary` DEFAULT CHARACTER SET utf8 ;
USE `mydiary` ;

-- -----------------------------------------------------
-- Table `mydiary`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydiary`.`status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydiary`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydiary`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NOT NULL,
  `user_password` TEXT NOT NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `status_id`),
  INDEX `fk_users_status1_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `mydiary`.`status` (`status_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydiary`.`biography`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydiary`.`biography` (
  `users_id` INT NOT NULL,
  `bio_surname` VARCHAR(45) NULL,
  `bio_name` VARCHAR(45) NULL,
  `bio_patronymic` VARCHAR(45) NULL,
  `bio_date` DATE NULL,
  PRIMARY KEY (`users_id`),
  CONSTRAINT `fk_biography_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydiary`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydiary`.`discs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydiary`.`discs` (
  `disc_id` INT NOT NULL AUTO_INCREMENT,
  `disc_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`disc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydiary`.`evals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydiary`.`evals` (
  `user_id` INT NOT NULL,
  `disc_id` INT NOT NULL,
  `eval_estimation` VARCHAR(2) NULL,
  `eval_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`, `disc_id`),
  INDEX `fk_evals_discs1_idx` (`disc_id` ASC) VISIBLE,
  CONSTRAINT `fk_evals_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydiary`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evals_discs1`
    FOREIGN KEY (`disc_id`)
    REFERENCES `mydiary`.`discs` (`disc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydiary`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydiary`.`groups` (
  `user_id` INT NOT NULL,
  `group` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_groups_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_groups_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydiary`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
